celines = [
    "Entrando Calisto vna huerta empos de vn falcon suyo fallo y a Melibea de cuyo amor preso començole de hablar: dela qual rigorosamente despedido: fue para su casa muy sangustiado.",
    "hablo con vn criado suyo llamado sempronio. el qual despues de muchas razones le endereço a vna vieja llamada celestina",
    "Calisto. En esto veo Melibea la grandeza de dios.\nMelibea. en que calisto.\nCalisto. en dar poder a natura que de tan perfeta hermosura te dotasse",
    "yo misto me alegro con recelo del esquiuo tormento que tu absencia me ha de causar.",
    "Melibea. por grand premio tienes esto calisto.",
    "Melibea. pues avn mas ygual galardon te dare yo si perseueras.\nCalisto. o bienauenturadas orejas mias que indignamente tan gran palabra haueys oydo.",
    "Calisto. yre como aquel contra quien solamente la aduersa fortuna pone su estudio con odio cruel.",
    "Calisto. assi los diablos te ganen assi por infortunio arrebatado perezcas",
    "Calisto. cierra la ventana & dexa la teniebla acompañar al triste & al desdichado la ceguedad: mis pensamientos tristes no son dignos de luz.",
    "O bienauenturada muerte aquella que deseada alos afligidos viene.",
    "Calisto. ve conel diablo.",
    "Calisto. vete de ay no me fables: si no quiça ante del tiempo de mi rabiosa muerte mis manos causaran tu arrebatado fin.",
    "O desauentura O subito mal: qual fue tan contrario acontescimiento que assi tan presto robo el alegria deste hombre: & lo que peor es junto conella el seso.",
    "mas vale que muera aquel a quien es enojosa la vida: que no yo que huelgo conella.",
    "asaz es señal mortal no querer sanar.",
    "desbraue. madure. que oydo he dezir que es peligro abrir o apremiar las postemas duras: porque mas se enconan.",
    "dexemos llorar al que dolor tiene: que las lagrimas & sospiros mucho desenconan el coraçon dolorido.",
    "que el sol mas arde donde puede re-uerberar.",
    "la vista a quien objecto no se antepone cansa: & quando aquel es cerca aguza se",
    "Avn que malo es esperar salud en muerte agena.",
    "por otra parte dizen los sabios que es grande descanso alos afligidos tener con quien puedan sus cuytas llorar.",
    "si possible es sanar sin arte ni aparejo: mas ligero es guarescer por arte: & por cura.",
    "Calisto. sempronio.\nSempronio. señor.\nCalisto. dame aca el laud.\nSempronio. señor ves le aqui.",
    "Calisto. qual dolor puede ser tal: que se yguale con mi mal.",
    "Sempronio. destemplado esta esse laud\nCalisto. como templara el destemplado. como sentira el armonia aquel que consigo esta tan discorde.",
    "Calisto. como sentira el armonia aquel que consigo esta tan discorde. aquel a quien la voluntad ala razon no obedece. quien tiene dentro del pecho aguijones.",
    "paz. guerra. tregua. amor. enemistad. injurias. pecados. sospechas. todo a vna causa.",
    "Pero tañe & canta la mas triste cancion que sepas.",
    "Sempronio. mira Nero de tarpeya a roma como se ardia: gritos dan niños & viejos: & el de nada se dolia.",
    "Sempronio. no me engaño yo que loco esta este mi amo.\nCalisto. que estas murmurando sempronio\nSempronio. no digo nada.",
    "Calisto. di lo que dizes no temas.",
    "mayor es la llama que dura ochenta años que la que en vn dia passa: & mayor la que mata vna anima que la que quema cient mill cuerpos.",
    "mas querria que mi spiritu fuesse conlos de los brutos animales: que por medio de aquel yr ala gloria delos sanctos.",
    "no basta loco sino ereje.",
    "Sempronio. digo que nunca dios quiera tal: que es especie de heregia lo que agora dixiste.",
    "Calisto. porque.\nSempronio. porque lo que dizes contradize la xpistiana religion.",
    "Sempronio. tu no eres xpistiano.\nCalisto. yo melibeo soy. & a Melibea adoro & en melibea creo: & a melibea amo.",
    "como melibea es grande: no cabe enel coraçon de mi amo que por la boca le sale a borbollones.",
    "bien se de que pie coxqueas: yo te sanare.",
    "Calisto. increyble cosa prometes.",
    "Que el comienço de la salud es conoscer hombre la dolencia del enfermo.",
    "Calisto. qual consejo puede regir lo que en si no tiene orden ni consejo.",
    "Sempronio. ha ha ha. esto es el fuego de calisto. Estas son sus congoxas. Como si solamente el amor contra el asestara sus tiros.",
    "O soberano dios quan altos son tus misterios. Quanta premia pusiste enel amor: que es necessaria turbacion enel amante.",
    "todos passan todos rompen: pungidos & esgarrochados como ligeros toros: sin freno saltan por las barreras.",
    "Mandaste al hombre por la muger dexar el padre & la madre",
    "Sempronio. de otro temple esta esta gayta.",
    "Calisto. que te paresce de mi mal.\nSempronio. que amas a melibea.\nCalisto. & no otra cosa.",
    "Sempronio. harto mal es tener la voluntad en vn solo lugar catiua.",
    "Sempronio. la perseuerancia enel mal no es constancia mas dureza o pertinacia la llaman en mi tierra.",
    "los filosofos de cupido llamalda como quisierdes.",
    "Sempronio. haz tu lo que bien digo & no lo que mal hago.",
    "Calisto. que me reprobas.\nSempronio. que sometes la dignidad del hombre ala imperfecion de la flaca muger.\nCalisto. muger: o grosero: dios dios.",
    "por dios la confiesso: & no creo que ay otro soberano enel cielo avn que entre nos otros mora.",
    "Sempronio. ha ha ha: oystes que blasfemia: vistes que ceguedad.\nCalisto. de que te ries.\nSempronio. riome que no pensaua que hauia peor inuencion de pecado que en sodoma.",
    "Calisto. porque amo a aquella ante quien tan indigno me hallo: que no la espero alcançar.",
    "Sempronio. o pusilanimo: o fi de puta que nembrot: que magno alexandre: los quales no solo del señorio del mundo: mas del cielo se juzgaron ser dignos.",
    "Calisto. no lo creo hablillas son.",
    "Calisto. maldito sea este necio & que porradas dize.",
    "lee los ystoriales: estudia los filosofos: mira los poetas: llenos estan los libros de sus viles & malos exemplos",
    "Oye a salomon. do dize que las mugeres & el vino hazen alos hombres renegar.",
    "escucha al aristoteles. mira a bernardo. gentiles. judios. xpistianos & moros todos enesta concordia estan.",
    "muchas houo & ay sanctas & virtuosas & notables cuya resplandesciente corona quita el general vituperio.",
    "que todo lo que piensan osan sin deliberar.",
    "su lengua su engaño. su oluido. su desamor. su ingratitud. su inconstancia. su testimoniar. su negar.",
    "su presuncion. su vana gloria. su abatimiento. su locura. su desden. su soberuia.",
    "su parleria. su golosina. su luxuria & suziedad. su miedo. su atreuemiento.",
    "sus hechizerias. sus embaymientos. sus escarnios. su deslenguamiento. su desuerguença. su alcahueteria.",
    "que aluañares debaxo de templos pintados.",
    "Por ellas es dicho arma del diablo cabeça de pecado: destruycion de parayso.",
    "las mugeres & el vino hazen los hombres renegar",
    "esta es la muger antigua malicia: que a Adam echo delos deleytes de parayso.",
    "Esta el linaje humano metio enel infierno.",
    "Huye de sus engaños. Sabes que fazen cosa que es dificil entender las.",
    "Alos que meten por los agujeros: denuestan enla calle.",
    "Ensañan se presto. apaciguan se luego.",
    "Quieren que adeuinen lo que quieren. O que plaga. o que enojo.",
    "aquel breue tiempo que son aparejadas de deleyte",
    "Calisto. ve mientra mas me dizes & mas inconuenientes me pones: mas la quiero",
    "miserable cosa es pensar ser maestro el que nunca fue discipulo.",
    "peor estremo es dexarse hombre caer de su merescimiento que poner se en mas alto lugar que deue",
    "eres hombre: & de claro ingenio: & mas a quien la natura doto delos mejores bienes que tuuo.",
    "fortuna medianamente partio contigo lo suyo: en tal quantidad: que los bienes que tienes de dentro conlos de fuera resplandescen",
    "Sempronio. alos que las vencieron querria que remedasses: que no alos que dellas fueron vencidos.",
    "Miras la nobleza & antiguedad de su linaje. el grandissimo patrimonio. el excelentissimo ingenio.",
    "la soberana hermosura: dela qual te ruego me dexes hablar vn poco",
    "que si delo oculto yo hablar te supiera: no nos fuera necessario altercar tan miserablemente estas razones.",
    "Sempronio. que mentiras & que locuras dira agora este cautiuo de mi amo.",
    "Asi te medre dios como me sera agradable esse sermon.",
    "Calisto. comienço por los cabellos. Uees tu las madexas del oro delgado que hilan en arabia: mas lindos son & no resplandecen menos",
    "Calisto. los ojos verdes rasgados. las pestañas luengas. las cejas delgadas & alçadas. la nariz mediana. la boca pequeña. los dientes menudos & blancos.",
    "los labrios colorados & grosezuelos. el torno del rostro poco mas luengo que redondo. el pecho alto. la redondeza & forma delas pequeñas tetas",
    "la tez lisa lustrosa. el cuero suyo escuresce la nieue. la color mezclada qual ella la escogio para si.",
    "Sempronio. en sus treze esta este necio.",
    "las manos pequeñas en mediana manera: de dulce carne acompañadas. los dedos luengos. las vñas en ellos largas & coloradas que parescen rubies entre perlas.",
    "mejor que la que paris juzgo entre las tres deesas.",
    "No as leydo el filosofo do dize. assi como la materia apetece ala forma: asi la mujer al varon.",
    "E porque no te desesperes yo quiero tomar esta empresa de complir tu desseo.",
    "impossible es fazer sieruo diligente el amo perezoso.",
    "Dias ha grandes que conozco en fin desta vezindad vna vieja barbuda que se dize Celestina hechizera astuta sagaz en quantas maldades ay.",
    "Entiendo que passan de cinco mill virgos: los que se han hecho & deshecho por su auctoridad enesta cibdad.",
    "Alas duras peñas promouera & prouocara a luxuria si quiere.",
    "Calisto. podria la yo fablar.",
    "Sempronio. yo te la traere hasta aca.",
    "sey le gracioso sey le franco.",
    "estudia mientra vo yo de le dezir tu pena: tan bien como ella te dara el remedio.",
    "te ruego que guies a mi sempronio: en manera que conuierta mi pena & tristeza en gozo",
    "Sempronio. madre bendita que desseo traygo gracias a dios que te me dexo ver.",
    "Celestina. fijo mio. rey mio turbado me has no te puedo fablar torna & da me otro abraço",
    "Elicia. ay triste que saltos me da el coraçon.",
    "Elicia. ay maldito seas traydor: postema & landre te mate: & a manos de tus enemigos mueras",
    "por crimines dignos de cruel muerte: en poder de rigurosa justicia te veas. ay ay.",
    "Sempronio. hy hy hy. que has mi elicia: de que te congoxas.",
    "nunca dios te vea. nunca dios te consuele ni visite.",
    "guay dela triste que en ti tiene su esperança & el fin de todo su bien.",
    "Sempronio. calla señora mia: tu piensas que la distancia del lugar es poderosa de apartar el entreñable amor",
    "el fuego que esta en mi coraçon. do yo vo comigo vas: comigo estas",
    "no te aflijas ni me atormentes mas delo que yo he padecido",
    "Celestina. anda aca dexa essa loca: que ella es liuiana: & turbada de tu absencia",
    "ven & fablemos no dexemos passar el tiempo en balde.",
    "Celestina. ay burlador.\nSempronio. dexa si soy burlador & muestra me la.",
    "los ojos se te salten que no basta a ti vna ni otra anda veela & dexa a mi para siempre.",
    "Sempronio. calla dios mio: & enojas te. que ni la quiero veer a ella ni a muger nascida. A mi madre quiero fablar: & queda te a dios.",
    "Elicia. anda anda: vete desconoscido: & esta otros tres años que no me bueluas a ver.",
    "Sempronio. madre mia bien ternas confiança & creeras que no te burlo.",
    "Toma el manto & vamos: que por el camino sabras lo que si aqui me tardasse en dezirte: empediria tu prouecho & el mio.",
    "se atenta: & ymagina enlo que te dixere: & no derrames tu pensamiento en muchas partes",
    "no derrames tu pensamiento en muchas partes: que quien junto en diuersos lugares le pone en ninguno le tiene: sino por caso determina lo cierto.",
    "quiero que sepas de mi lo que no has oydo.",
    "que jamas pude despues que mi fe contigo puse: desear bien de que no te cupiesse parte.",
    "Celestina. parta dios fijo delo suyo contigo. que no sin causa lo hara: si quiera porque has piedad desta pecadora de vieja.",
    "Pero di no te detengas: que la amistad que entre ti & mi se afirma no ha menester preambulos",
    "la amistad que entre ti & mi se afirma no ha menester preambulos: ni correlarios: ni aparejos para ganar voluntad.",
    "Abreuia & ven al fecho: que vanamente se dize por muchas palabras: lo que por pocas se puede entender.",
    "Sempronio. assi es Calisto arde en amores de Melibea: de ti & de mi tiene necessidad pues juntos nos ha menester: juntos nos aprouechemos.",
    "que conoscer el tiempo & vsar el hombre dela oportunidad haze los hombres prosperos.",
    "Celestina. bien as dicho: al cabo estoy",
    "Digo que me alegro destas nueuas: como los cirujanos delos descalabrados.",
    "me alegro destas nueuas: como los cirujanos delos descalabrados. E como aquellos dañan enlos principios las llagas: & encarecen el prometimiento dela salud: assi entiendo yo fazer a Calisto",
    "El esperança luenga aflige el coraçon. & quanto el la perdiere tanto gela promete. bien me entiendes.",
    "Sempronio. callemos que ala puerta estamos: & como dizen las paredes han oydos.",
    "Parmeno. señor sempronio & vna puta vieja alcoholada dauan aquellas porradas.\nCalisto. calla calla maluado: que es mi tia. corre corre abre.",
    "siempre lo vi que por huyr hombre de vn peligro cae en otro mayor.",
    "Si entre cient mugeres va & alguno dize puta vieja: sin ningun empacho luego buelue la cabeça: & responde con alegre cara.",
    "Enlos combites. enlas fiestas. enlas bodas. enlas confradias. enlos mortuorios. en todos los ayuntamientos de gentes: conella passan tiempo",
    "si passa por los perros: aquello suena su ladrido. si esta cerca las aues otra cosa no cantan.",
    "si cerca los ganados balando lo pregonan si cerca las bestias rebuznando dizen puta vieja.",
    "las ranas delos charcos otra cosa no suelen mentar.",
    "si va entre los herreros aquello dizen sus martillos.",
    "Cantan la los carpinteros. peynan la los peynadores. texedores. labradores. enlas huertas. enlas aradas. enlas viñas. enlas segadas: conella passan el afan cotidiano.",
    "Dias grandes son passados que mi madre muger pobre moraua en su vezindad: la qual rogada por esta Celestina me dio a ella por siruiente",
    "Tiene esta buena dueña al cabo dela cibdad alla cerca delas tenerias: enla cuesta del rio: vna casa apartada medio cayda poco compuesta & menos abastada.",
    "Ella tenia seys oficios. conuiene a saber labrandera perfumera maestra de fazer afeytes & de fazer virgos alcahueta & vn poquito hechizera.",
    "ninguna venia sin torrezno. trigo. harina. o jarro de vino: & delas otras prouisiones que podian a sus amas furtar",
    "Asaz era amiga de estudiantes & despenseros: & moços de abades.",
    "hombres descalços contritos & reboçados desatacados: que entrauan alli a llorar sus pecados.",
    "ya viene el ama de todos muy conocida.",
    "Con todos estos afanes nunca pasaua sin missa ni bisperas: ni dexaua monesterios de frayles ni de monjas.",
    "Adelgazaua los cueros con çumos de limones con turuino con tuetano de corço: & de garça: & otras confaciones.",
    "Sacaua aguas para oler de rosas de azahar: de jasmin de trebol de madreseluia & clauellinas mosquetas & almizcladas. poluorizadas con vino.",
    "Hazia lexias para enrubiar de sarmientos de carrasca de centeno de marrubios con salitre con alumbre & millifolia & otras diuersas cosas.",
    "E los vntos & mantecas que tenia es hastio de dezir. de vaca de osso de cauallos & de camellos de culebra & de conejo",
    "Aparejos para baños esto es vna marauilla: delas yeruas & rayzes que tenia enel techo de su casa colgadas. mançanilla & romero maluauiscos. culantrillo. coronillas. flor de sauco. & de mostaza. espliego. & laurel blanco.",
    "Los azeytes que sacaua para el rostro no es cosa de creer. de estoraque & de jazmin. de limon de pepitas de violetas. de menjuy. de alfocigos de piñones de granillo. de açofeyfas. de neguilla de altramuzes de aruejas & de carillas.",
    "E vn poquillo de balsamo tenia ella en vna redomilla que guardaua para aquel rascuño que tiene por las narizes.",
    "Esto delos virgos vnos fazia de bexiga: & otros curaua de punto.",
    "Hazia con esto marauillas: que quando vino por aqui el embaxador frances: tres vezes vendio por virgen vna criada que tenia.",
    "remediaua por caridad muchas huerfanas & erradas que se encomendauan a ella.",
    "Tenia uessos de coraçon de cieruo. lengua de biuora. cabeças de codornizes: sesos de asno. tela de cauallo. mantillo de niño. haua morisca. guija marina. soga de ahorcado. flor de yedra espina de erizo.",
    "Uenian a ella muchos hombres & mugeres. & a vnos demandaua el pan do mordian. a otros de su ropa. a otros de sus cabellos. a otros pintaua enla palma letras con açafran.",
    "a otros daua vnos coraçones de cera llenos de agujas quebradas. & otras cosas en barro & en plomo hechas muy espantables al ver.",
    "Pintaua figuras. dezia palabras en tierra. quien te podra dezir lo que esta vieja fazia. & todo era burla & mentira.",
    "Calisto. bien esta parmeno: dexa lo para mas oportunidad. asaz soy de ti auisado",
    "no nos detengamos: que la necessidad desecha la tardança.",
    "Yo temo: & el temor reduze la memoria",
    "Parmeno. quexo me calisto dela dubda de mi fidelidad & seruicio",
    "no me congoxes ni me importunes: que sobre cargar el cuydado es aguijar al animal congoxoso.",
    "Pues cree que yo no vine aca por dexar este pleyto indeciso",
    "Tiempla te & no te apresures: que muchos con codicia de dar enel fiel yerran el blanco.",
    "Avn que soy moço cosas he visto asaz: & el seso & la vista delas muchas cosas demuestran la experiencia",
    "Celestina. calla que para la mi santiguada: do vino el asno vendra el albarda.",
    "que los bienes si no son comunicados no son bienes.",
    "Ganemos todos: partamos todos: holguemos todos",
    "yo te le traere manso & benigno a picar el pan en el puño.",
    "por la philosomia es conocida la virtud interior.",
    "O vejez virtuosa o virtud enuejecida.",
    "Dende aqui adoro la tierra que huellas: & en reuerencia tuya beso.",
    "dile que cierre la boca & comience abrir la bolsa: que delas obras dudo quanto mas delas palabras",
    "Parmeno. guay de orejas que tal oyen. Perdido es quien tras perdido anda.",
    "O calisto desauenturado abatido ciego: & en tierra esta adorando ala mas antigua & puta tierra: que fragaron sus espaldas en todos los burdeles.",
    "deshecho es. vencido es. caydo es. no es capaz de ninguna redencion ni consejo ni esfuerço.",
    "vamos: que no se deue dexar crescer la yerua entre los panes: ni la sospecha enlos coraçones delos amigos.",
    "no se deue dexar crescer la yerua entre los panes: ni la sospecha enlos coraçones delos amigos. Sino alimpiar la luego conel escardilla delas buenas obras.",
    "Calisto. astuto hablas: vamos & no tardemos.",
    "por que virtud nos amonesta sufrir las tentaciones: & no dar mal por mal.",
    "bien te oy: & no pienses que el oyr conlos otros exteriores sesos mi vejez aya perdido",
    "que no solo lo que veo oyo & conozco: mas avn lo intrinseco conlos intellectuales ojos penetro.",
    "Has de saber parmeno que calisto anda de amor quexoso: & no lo juzgues por eso por flaco: que el amor imperuio todas las cosas vence.",
    "que dos conclusiones son verdaderas La primera que es forçoso el hombre amar ala muger: & la muger al hombre. La segunda que el que verdaderamente ama es necessario que se turbe: conla dulçura del soberano deleyte",
    "que el que verdaderamente ama es necessario que se turbe: conla dulçura del soberano deleyte: que por el hazedor delas cosas fue puesto: porque el linaje delos hombres perpetuase",
    "E no solo enla humana especie: mas enlos pesces enlas bestias enlas aues: enlas reptilias.",
    "Que diras a esto parmeno: neciuelo loquito angelico perlica simplezico. lobitos en tal gestico: llega te aca putico que no sabes nada del mundo: ni de sus deleytes",
    "mal sosegadilla deues tener la punta de la barriga.",
    "Celestina. [...] mal sosegadilla deues tener la punta de la barriga.\nParmeno. como cola de alacran.\nCelestina. & avn peor que la otra muerde sin hinchar & la tuya hincha por nueue meses.\nParmeno. hy hy hy.",
    "Parmeno. hy hy hy.\nCelestina. ries te: landrezilla fijo.",
    "Parmeno. calla madre no me culpes ni me tengas avn que moço por insipiente.",
    "Amo a calisto porque le deuo fidelidad por criança: por beneficios: por ser del honrrado & bien tratado",
    "veo le perdido & no ay cosa peor que yr tras desseo sin esperança de buen fin",
    "Celestina. parmeno tu no vees que es necedad o simpleza llorar por lo que con llorar no se puede remediar.",
    "pero assi perdida ya la esperança: pierdo el alegria & lloro.",
    "Celestina. lloraras sin prouecho: por lo que llorando estoruar no podras: ni sanar lo presumas. A otros no ha contecido esto parmeno.",
    "porque enlos bienes mejor es el acto que la potencia: & enlos males mejor la potencia que el acto.",
    "assi que mejor es ser sano que poder lo ser.",
    "Celestina. putos dias viuas vellaquillo: & como te atreues.",
    "Celestina. jesu jesu jesu. E tu eres parmeno hijo dela Claudiana.\nParmeno. alahe yo.",
    "Celestina. pues fuego malo te queme: que tan puta vieja era tu madre como yo",
    "allega te a mi: ven aca que mill açotes & puñadas te di eneste mundo: & otros tantos besos. Acuerdas te quando dormias a mis pies loquito.",
    "Celestina. mala landre te mate: & como lo dize el desuergonçado. Dexadas burlas & pasatiempos: oye agora mi fijo & escucha",
    "que avn que a vn fin soy llamada a otro so venida",
    "la fe es de guardar mas que alos viuos alos muertos que no pueden hazer por si",
    "en pesquisa & seguimiento tuyo yo he gastado asaz tiempo & quantias",
    "Los peregrinos tienen muchas posadas & pocas amistades. Por que en breue tiempo con ninguno no pueden firmar amistad.",
    "E el que esta en muchos cabos no esta en ninguno.",
    "ni ay cosa que mas la sanidad impida que la diuersidad & mudança & variacion delos manjares.",
    "nunca la llaga viene a cicatrizar: enla qual muchas melezinas se tientan.",
    "ni conualesce la planta que muchas vezes es traspuesta.",
    "ni ay cosa tan prouechosa que en llegando aproueche",
    "por tanto mi hijo dexa los impetos dela juuentud: & torna te conla doctrina de tus mayores ala razon",
    "reposa en alguna parte: & donde mejor que en mi voluntad. en mi animo. en mi consejo",
    "E tu gana amigos que es cosa durable: ten con ellos constancia. no viuas en flores.",
    "dexa los vanos prometimientos de los señores: los quales desechan la substancia de sus siruientes con huecos & vanos prometimientos: como la sanguijuela saca la sangre: desagradescen. injurian. oluidan seruicios. niegan galardon.",
    "Guay de quien en palacio enuejece: como se escriue dela probatica piscina: que de ciento que entrauan sanaua vno.",
    "Estos señores deste tiempo mas aman a si que alos suyos & no yerran: los suyos ygualmente lo deuen hazer.",
    "perdidas son las mercedes. las magnificencias. los actos nobles.",
    "cada vno destos catiuan & mezquinamente procuran su interesse conlos suyos",
    "porque este tu amo como dizen me parece rompe necios: de todos se quiere seruir sin merced",
    "creeme en su casa cobra amigos que es el mayor precio mundano",
    "Parmeno. celestina todo tremo de oyrte: no se que haga: perplexo esto: por vna parte tengo te por madre: por otra a calisto por amo.",
    "Riqueza desseo. pero quien torpemente sube alo alto: mas ayna caye que subio.",
    "A tuerto o a derecho nuestra casa hasta el techo.",
    "tengo por onesta cosa la pobreza alegre. E avn mas te digo que no los que poco tienen son pobres: mas los que mucho dessean",
    "querria pasar la vida sin embidia: los yermos & aspereza sin temor: el sueño sin sobresalto: las injurias con respuesta las fuerças sin denuesto: las premias con resistencia.",
    "Celestina. o hijo bien dizen que la prudencia no puede ser sino enlos viejos: & tu mucho eres moço.",
    "Parmeno. mucho segura es la mansa pobreza.",
    "Celestina. mas di como mayor: que la fortuna ayuda alos osados.",
    "bienes tienes: & no sabes que has menester amigos para los conseruar",
    "que quanto mayor es la fortuna tanto es menos segura: & por tanto en los infortunios el remedio es alos amigos.",
    "tres maneras de amistad concurren. Conuiene a saber por bien & prouecho & deleyte.",
    "como seays en edad dispuestos para todo linaje de plazer: en que mas los moços que los viejos se juntan. Assi como para jugar. para vestir. para burlar. para comer & beuer. para negociar amores juntos de compañia.",
    "Parmeno. mi fe madre no creo a nadie.\nCelestina. estremo es creer a todos: & yerro no creer a ninguno.",
    "Celestina. o mezquino de enfermo coraçon es no poder sufrir el bien.",
    "Da dios hauas aquien no tiene quixadas.",
    "adonde ay mayor entendimiento: ay menor fortuna & donde mas discrecion alli es menor la fortuna",
    "oydo he a mis mayores que vn exemplo de luxuria o auaricia mucho mal haze: & que con aquellos deue hombre conuersar que le fagan mejor: &",
    "aquellos dexar a quien el mejores piensa hazer.",
    "E si hombre vencido del deleyte va contra la virtud no se atreua ala honestad.",
    "Celestina. sin prudencia hablas: que de ninguna cosa es alegre possession sin compañia.",
    "no te retrayas ni amargues que la natura huye lo triste & apetece lo delectable.",
    "El deleyte es conlos amigos enlas cosas sensuales: & especial en recontar las cosas de amores: & comunicar las.",
    "Esto hize: esto otro me dixo: tal donayre passamos: de tal manera la tome: assi la bese: assi me mordio: assi la abrace: assi se allego. O que fabla. o que gracia. o que juegos.",
    "o que gracia. o que juegos. o que besos. Uamos alla. boluamos aca. ande la musica. pintemos los motes. canten canciones. inuenciones. justemos. que cimera sacaremos. o que letra.",
    "rondemos su calle. mira su carta. vamos de noche. ten me el escala. aguarda ala puerta. como te fue. cata el cornudo sola la dexa dale otra buelta.",
    "alahe alahe: la que las sabe las tañe.",
    "este es el deleyte: que lo al mejor fazen los asnos en el prado.",
    "E dela discrecion mayor es la prudencia. & la prudencia no puede ser sin esperimento: & la esperiencia no puede ser mas que enlos viejos.",
    "E los buenos padres bien aconsejan a sus hijos: & especial yo a ti: cuya vida & honrra mas que la mia deseo.",
    "E quando me pagaras tu esto nunca: pues alos padres & alos maestros no puede ser fecho seruicio ygualmente.",
    "Parmeno. todo me recelo madre de recebir dudoso consejo.",
    "yerro es no creer: & culpa creer lo todo.",
    "humano es confiar: mayormente enesta que interesse promete",
    "Oydo he que deue hombre a sus mayores creer",
    "La paz no se deue negar que bienauenturados son los pacificos: que fijos de dios seran llamados.",
    "Amor no se deue rehuyr: caridad alos hermanos interesse pocos le apartan.",
    "Madre no se deue ensañar el maestro dela ignorancia del discipulo: si no raras vezes",
    "Celestina. delos hombres es errar & bestial es la porfia.",
    "gozo me parmeno que ayas limpiado las turbias telas de tus ojos",
    "O que persona o que hartura o que cara tan venerable.",
    "Que dos en vn coraçon viuiendo son mas poderosos de hazer & de entender.",
    "Celestina. como enel oro muy fino labrado por la mano del sotil artifice: la obra sobrepuja ala materia: asi se auentaja a tu magnifico dar la gracia & forma de tu dulce liberalidad",
    "sin duda la presta dadiua su efeto ha doblado: porque la que tarda el prometimiento muestra negar: & arrepentir se del don prometido.",
    "para que es la fortuna fauorable & prospera: sino para seruir ala honrra que es el mayor delos mundanos bienes",
    "que aprouecha tener lo que se niega aprouechar: sin dubda te digo que es mejor el vso delas riquezas que la possesion dellas.",
    "O que glorioso es el dar: o que miserable es el recebir: quanto es mejor el acto que la posession: tanto es mas noble el dante quel recibiente.",
    "Entre los elementos el fuego por ser mas actiuo es mas noble",
    "E dizen algunos que la nobleza es vna alabança que prouiene delos merecimientos & antiguedad delos padres: yo digo que la agena luz nunca te hara claro si la propia no tienes",
    "E por tanto no te estimes enla claridad de tu padre que tan magnifico fue sino enla tuya: & assi se gana la honrra: que es el mayor bien delos que son fuera de hombre.",
    "Porende goza de hauer seydo assi magnifico & liberal & de mi consejo torna te ala camara & reposa pues que tu negocio en tales manos esta depositado.",
    "pues el comienço lleuo bueno: el fin sera muy mejor",
    "dizes desuarios de hombre sin seso. sospirando. gimiendo mal trobando. holgando conlo escuro. deseando soledad buscando nueuos modos de pensatiuo tormento",
    "holgando conlo escuro. deseando soledad buscando nueuos modos de pensatiuo tormento",
    "si perseueras o de muerto o loco no podras escapar: si siempre no te acompaña quien te allegue plazeres: diga donayres. tanga canciones alegres. cante romances.",
    "juegue a naypes. arme mates. finalmente que sepa buscar todo genero de dulce passa tiempo",
    "no dexar trasponer tu pensamiento en aquellos crueles desuios que rescebiste de aquella señora enel primer trance de tus amores.",
    "no sabes que aliuia la pena llorar la causa quanto es dulce alos tristes quexar su passion",
    "quanto descanso traen consigo los quebrantados sospiros: quanto relieuan & diminuyen los lagrimosos gemidos el dolor",
    "Sempronio. lee mas adelante. buelue la hoja",
    "enel contemplar esta la pena de amor: enel oluidar el descanso",
    "huye de tirar cozes al aguijon: finge alegria & consuelo & ser lo ha: que muchas vezes la opinion trae las cosas donde quiere: no para que mude la verdad: pero para moderar nuestro sentido & regir nuestro juyzio.",
    "que tanta es la fuerça dela verdad que las lenguas delos enemigos trae a si.",
    "Parmeno. porque aquien dizes el secreto das tu libertad",
    "que quando ay mucha distancia del que ruega al rogado o por grauedad de obediencia o por señorio de estado o esquiuidad de genero: como entre esta mi señora & mi: es necessario intercessor o medianero",
    "Parmeno. aprueue lo el diablo.",
    "Parmeno. digo señor que nunca yerro vino desacompañado: & que vn inconueniente es causa & puerta de muchos.",
    "la habla engendro amor: el amor pario tu pena: la pena causara perder tu cuerpo & alma & hazienda",
    "lo que mas dello siento es venir a manos de aquella trotaconuentos despues de tres vezes emplumada.",
    "sin pena hablas: no te duele donde a mi parmeno.",
    "no sabes que el primer escalon de locura es creer se ser sciente",
    "si tu sintiesses mi dolor con otra agua rociarias aquella ardiente llaga que la cruel frecha de cupido me ha causado",
    "eres vn terron de lisonja. bote de malicias. el mismo meson & aposentamiento dela embidia",
    "pues sabe que esta mi pena & flutuoso dolor no se rige por razon: no quiere auisos carece de consejo",
    "valiera mas solo que mal acompañado.",
    "Parmeno. señor flaca es la fidelidad que temor de pena la conuierte en lisonja",
    "quitar se ha el velo de la ceguedad: passaran estos momentaneos fuegos",
    "conosceras mis agras palabras ser mejores para matar este fuerte cancre",
    "Calisto. calla calla perdido: esto yo penando & tu filosofando",
    "saquen vn cauallo limpien le mucho: aprieten bien la cincha; porque si pasare por casa de mi señora & mi dios.",
    "o desdichado de mi por ser leal padezco mal: otros se ganan por malos yo me pierdo por bueno: el mundo es tal.",
    "el mundo es tal. quiero yr me al hilo dela gente: pues alos traydores llaman discretos: alos fieles nescios",
    "si yo creyera a celestina con sus seys dozenas de años a cuestas: no me maltratara calisto: mas esto me porna escarmiento daqui adelante conel: que si dixere comamos: yo tambien.",
    "Si quisiere derrocar la casa: aprouarlo. si quemar su hazienda: yr por fuego. destruya. rompa. quiebre. dañe.",
    "pues dizen a rio buelto ganancia de pescadores. nunca mas perro al molino.",
    "A dineros pagados braços quebrados.",
    "Celestina. no es cosa mas propia del que ama que la impaciencia: toda tardança les es tormento: niguna dilacion les agrada.",
    "avn al diablo daria yo sus amores: al primer desconcierto que vea eneste negocio no como mas su pan",
    "mas vale perder lo seruido que la vida por cobrallo",
    "si te parece madre guardemos nuestras personas de peligro",
    "si la ouiere ogaño: si no otro año",
    "que no ay cosa tan dificile de çofrir en sus principios: que el tiempo no la ablande: & faga comportable",
    "niguna llaga tanto se sintio que por luengo tiempo no afloxase su tormento ni plazer tan alegre fue que no le amengue su antiguedad",
    "el mal & el bien: la prosperidad & aduersidad: la gloria & pena: todo pierde conel tiempo la fuerça de su acelerado principio",
    "los casos de admiracion & venidos con gran desseo tan presto como passados oluidados: cada dia vemos nouedades: & las oymos: & las passamos & dexamos atras: diminuye las el tiempo: faze las contingibles.",
    "Que tanto te marauillarias si dixesen la tierra temblo. o otra semejante cosa que no oluidases luego: assi como elado esta el rio: el ciego vee: ya",
    "muerto es tu padre: vn rayo cayo: ganada es granada: el rey entra oy",
    "todo es assi: todo passa desta manera: todo se oluida: todo queda atras",
    "pues assi sera este amor de mi amo: quanto mas fuere andando: tanto mas diminuyendo: procuremos prouecho mientra pendiere la contienda",
    "mas vale que pene el amo que no que peligre el moço.",
    "Celestina. bien as dicho contigo estoy: agradado me has: no podemos errar",
    "por los presentes que lo vieren: no digan que se gana holgando el salario",
    "Sempronio. haz a tu voluntad: que no sera este el primer negocio que has tomado a cargo.",
    "hijo: pocas virgines a dios gracias has tu visto enesta cibdad que hayan abierto tienda a vender: de quien yo no aya sido corredora de su primer hilado",
    "en nasciendo la mochacha la hago escriuir en mi registro: para saber quantas se me salen dela red: que pensauas. auia me de mantener del viento",
    "que pensauas. auia me de mantener del viento: herede otra herencia: tengo otra casa o viña. conoces me otra hazienda mas deste oficio: de que como & beuo: de que visto & calço",
    "enesta cibdad nascida enella criada: manteniendo honrra como todo el mundo sabe.",
    "quien no supiere mi nombre & mi casa tenle por estrangero.",
    "Celestina. dixe le el sueño & la soltura: & como ganaria mas con nuestra compañia que conlas lisonjas que dize a su amo. como viuiria siempre pobre & baldonado: sino mudaua el consejo: que no se hiziesse sancto a tal perra vieja como yo",
    "Celestina. aqui esta celestina que le vido nascer: & le ayudo a criar: su madre & yo vña & carne: della aprendi todo lo mejor que se de mi oficio.",
    "juntas comiamos. juntas dormiamos. juntas hauiamos nuestros solazes: nuestros plazeres: nuestros consejos & conciertos:",
    "en casa & fuera como dos hermanas: nunca blanca gane en que no touiesse su meytad.",
    "o muerte muerte: a quantos priuas de agradable compañia: a quantos desconsuela tu enojosa visitacion: por vno que comes con tiempo: cortas mil en agraz",
    "que siendo ella viua no fueran estos mis passos desacompañados: buen siglo aya: que leal amiga & buena compañera me fue",
    "pero yo le hare de mi fierro si viuo. yo le contare enel numero delos mios.",
    "Celestina. no ay çurujano que ala primera cura juzgue la herida.",
    "melibea es hermosa: calisto loco & franco ni a el penara gastar ni a mi andar. bulla moneda: & dure el pleyto lo que durare: todo lo puede el dinero",
    "bulla moneda: & dure el pleyto lo que durare",
    "todo lo puede el dinero: las peñas quebranta: los rios passa en seco: no ay lugar tan alto que vn asno cargado de oro no le suba.",
    "Su desatino & ardor basta para perder a si & ganar a nos otros",
    "Su desatino & ardor basta para perder a si & ganar a nos otros: esto he sentido: esto he calado: esto se del & della: esto es lo que nos ha de aprouechar.",
    "que avn que este braua melibea: no es esta si a dios ha plazido la primera a quien yo he hecho perder el cacarear",
    "coxquillocicas son todas: mas despues que vna vez consienten la silla enel enues del lomo: nunca querrian folgar: por ellas queda el campo.",
    "si de noche caminan nunca querrian que amaneciesse. maldizen los gallos porque annuncian el dia",
    "nunca me vi cansada: & avn assi vieja como soy: sabe dios mi buen deseo",
    "hazen se sieruas de quien eran señoras: dexan el mando & son mandadas",
    "alos chirriadores quicios delas puertas hazen con azeytes vsar su oficio sin ruydo.",
    "no te sabre dezir lo mucho que obra enellas aquel dulçor que les queda delos primeros besos de quien aman.",
    "Son enemigas todas del medio: contino estan posadas enlos estremos.",
    "Sempronio. no te entiendo essos terminos madre.\nCelestina. digo que la muger o ama mucho aquel de quien es requerida o le tiene grande odio",
    "la muger o ama mucho aquel de quien es requerida o le tiene grande odio: assi si al querer despiden no pueden tener las riendas al desamor.",
    "porque se que avn que al presente la ruegue: al fin me ha de rogar: avn que al principio me amenaze al cabo me ha de halagar.",
    "Aqui lleuo vn poco de hilado enesta mi faltriquera: con otros aparejos que comigo siempre traygo",
    "Sempronio. madre mira bien lo que hazes: porque quando el principio se yerra no puede seguir se buen fin",
    "piensa en su padre que es noble & esforçado: su madre celosa & braua: tu la misma sospecha.",
    "en pensallo tiemblo no vayas por lana & vengas sin pluma.",
    "quando tu nasciste ya comia yo pan con corteza",
    "es comun condicion humana que lo que mucho se dessea jamas se piensa ver concluydo",
    "Elicia. santiguar me quiero sempronio: quiero hazer vna raya enel agua: que nouedad es esta venir oy aca dos vezes.",
    "abre el arca delos lizos: & hazia la mano derecha hallaras vn papel escrito con sangre de morciegalo",
    "Elicia. madre no esta donde dizes: jamas te acuerdas a cosa que guardas.\nCelestina. no me castigues por dios a mi vegez: no me maltrates elicia.",
    "Entra enla camara delos vnguentos & enla pelleja del gato negro donde te mande meter los ojos dela loba le fallaras",
    "Celestina. conjuro te triste pluton señor dela profundidad infernal: emperador dela corte dañada: capitan soberuio delos condennados angeles",
    "señor delos sulfureos fuegos que los heruientes etnicos montes manan. gouernador & veedor delos tormentos & atormentadores delas pecadoras animas.",
    "Yo celestina tu mas conocida clientula te conjuro por la virtud & fuerça destas vermejas letras.",
    "E conello de tal manera quede enredada: que quanto mas lo mirare tanto mas su coraçon se ablande",
    "si no lo hazes con presto mouimiento ternas me por capital enemiga",
    "aquellas cosas que bien no son pensadas: avn que algunas vezes ayan buen fin comunmente crian desuariados efetos",
    "assi que la mucha especulacion nunca carece de buen fruto.",
    "Pues amargas cient monedas serian estas.",
    "ay cuytada de mi en que lazo me he metido: que por me mostrar solicita & esforçada pongo mi persona al tablero",
    "o dubdosa & dura perplexidad: no se qual escoja por mas sano: enel osar manifiesto peligro: enla couardia denostada perdida",
    "a donde yra el buey que no are.",
    "Cada camino descubre sus dañosos & hondos barrancos.",
    "calisto que dira. que hara. que pensara. sino que ay nueuo engaño en mis pisadas.",
    "puta vieja porque acrecentaste mis pasiones: con tus promessas.",
    "Alcahueta falsa: para todo el mundo tienes pies: para mi lengua: para todos obra: para mi palabras",
    "para todos luz: para mi tiniebla.",
    "mal aca mal aculla: pena en ambas partes: quando alos estremos falta el medio",
    "Pues jamas al esfuerço desayudo la fortuna.",
    "esfuerça esfuerça celestina no desmayes: que nunca faltan rogadores para mitigar las penas.",
    "Todos los agueros se adereçan fauorables: o yo no se nada desta arte: quatro hombres que he topado alos tres llaman juanes: & los dos son cornudos.",
    "ni perro me ha ladrado: ni aue negra he visto",
    "Celestina. paz sea enesta casa.\nLucrecia. celestina madre seas bien venida: qual dios te traxo por estos barrios no acostumbrados.",
    "Lucrecia. a esso solo saliste de tu casa: marauillo me de ti que no es essa tu costumbre: ni sueles dar passo sin prouecho.",
    "en mi seso estoy: que nunca metes aguja sin sacar reja.",
    "si tu me das entender lo incognito por lo menos conocido: es coger agua en cesto.",
    "vendia las moças alos abades & descasaua mill casados.",
    "conoce mucho en yeruas. cura niños. & avn algunos la llaman la vieja lapidaria.",
    "mis passiones & enfermedades han impedido mi visitar tu casa como era razon: mas dios conoce mis limpias entrañas: mi verdadero amor",
    "que la distancia delas moradas no despega el querer delos coraçones",
    "me sobreuino mengua de dinero: no supe mejor remedio que vender vn poco de hilado",
    "delgado como el pelo dela cabeça: ygual. rezio como cuerdas de vihuela. blanco como el copo dela nieue: hilado todo por estos pulgares",
    "Celestina. por aqui anda el diablo aparejando oportunidad",
    "Celestina. yo te prometo señora en yendo de aqui me vaya por essos monesterios: donde tengo frayles deuotos mios & les de el mismo cargo que tu me das",
    "Celestina. señora el perdon sobraria donde el yerro falta",
    "dios la dexe gozar su noble juuentud & florida mocedad: que es el tiempo en que mas plazeres & mayores deleytes se alcançaran",
    "la vejez no es sino meson de enfermedades: posada de pensamientos: amiga de renzillas: congoxa continua: llaga incurable. manzilla delo passado. pena delo presente. cuydado triste delo por venir. vezina dela muerte.",
    "Melibea. bien conozco que dize cada vno dela feria segund le va en ella.",
    "Celestina. señora hija a cada cabo ay tres leguas de mal quebranto.",
    "Cada rico tiene vna dozena de hijos & nietos: que no rezan otra oracion: no otra peticion sino rogar a dios: que le saque den medio: no veen la hora que tener a el so la tierra: & lo suyo entre sus manos",
    "Celestina. loco es señora el caminante: que enojado del trabajo del dia quisiesse boluer de comienço la jornada para tornar otra vez aquel lugar",
    "que todas aquellas cosas cuya possession no es agradable: mas vale poseellas que esperallas: porque mas cerca esta el fin dellas: quanto mas andado del comienço.",
    "No ay cosa mas dulce ni graciosa al muy cansado que el meson assi que avn que la moçedad sea alegre: el verdadero viejo no la dessea: porque el que de corazon & seso carece: quasi otra cosa no ama sino lo que perdio.",
    "Celestina. tan presto señora se va el cordero como el carnero: niguno es tan viejo que no pueda viuir vn año: ni tan moço que oy no pudiesse morir",
    "Melibea. Di me madre eres tu celestina la que solia morar alas tenerias cabe el rio.\nCelestina. señora hasta que dios quiera.",
    "figura se me que eras hermosa: otra pareces: muy mudada estas.",
    "Melibea. que hablas loca: que es lo que dizes: de que te ries.",
    "ten tu el tiempo que no ande terne yo mi forma que no se mude.",
    "No has leydo que dizen verna el dia que enel espejo no te conozcas",
    "yo encaneci temprano: & parezco de doblada edad: que assi goze desta alma pecadora: & tu desse cuerpo gracioso: que de quatro hijas que pario mi madre yo fuy la menor: mira como no so vieja como me juzgan",
    "celestina amiga yo he holgado mucho en verte & conoscerte: tambien has me dado plazer con tus razones toma tu dinero & vete con dios: que me parece que no deues hauer comido.",
    "Celestina. o angelica ymagen o perla preciosa",
    "por la diuina boca fue dicho: contra aquel infernal tentador: que no de solo pan viuiremos",
    "no el solo comer mantiene: mayormente a mi: que me suelo estar vno & dos dias negociando encomiendas agenas ayuna",
    "esto tuue siempre querer mas trabajar siruiendo a otros: que holgar contentando ami.",
    "la necessitada causa de mi venida que es otra que la que fasta agora as oydo: & tal que todos perderiamos en me tornar en balde sin que la sepas.",
    "Melibea. di madre todas tus necessidades: que si yo las pudiere remediar de muy buen grado lo hare por el passado conoscimiento & vezindad: que pone obligacion alos buenos.",
    "que las mias de mi puerta adentro me las passo: sin que las sienta la tierra: comiendo quando puedo: beuiendo quando lo tengo",
    "que con mi pobreza jamas me falto a dios gracias vna blanca para pan: & vn quarto para vino",
    "jamas me acoste sin comer vna tostada en vino: & dos dozenas de soruos por amor dela madre tras cada sopa",
    "assi que donde no ay varon todo bien fallesce. con mal esta el huso quando la barua no anda desuso.",
    "Celestina. donzella graciosa & de alto linaje: tu suaue fabla & alegre gesto: junto conel aparejo de liberalidad que muestras con esta pobre vieja: me dan osadia a te lo dezir.",
    "con sola vna palabra de tu noble boca salida: que le lleue metida en mi seno tiene por fe que sanara: segun la mucha deuocion tiene en tu gentileza.",
    "por vna parte me alteras & prouocas a enojo: por otra me mueues a compasion",
    "dizen: que el que puede sanar al que padece: no lo faziendo le mata",
    "Celestina. el temor perdi mirando señora tu beldad: que no puedo creer que embalde pintasse dios vnos gestos mas perfetos que otros: mas dotados de gracias: mas hermosas faciones: sino para fazer los almazen de virtudes",
    "pues como todos seamos humanos: nascidos para morir. sea cierto que no se puede dezir nacido: el que para si solo nascio. Porque seria semejante alos brutos animales",
    "como se dize del vnicornio: que se humilla a qualquiera donzella",
    "niguna cosa el gallo come: que no participe & llame las gallinas a comer dello.",
    "porque no daremos parte de nuestras gracias & personas alos proximos: mayormente quando estan embueltos en secretas enfermedades",
    "donde esta la melezina: salio la causa dela enfermedad.",
    "Melibea. por dios que sin mas dilatar me digas quien es esse doliente",
    "Celestina. bien ternas señora noticia enesta cibdad de vn cauallero mancebo: gentil hombre: de clara sangre que llaman calisto.\nMelibea. ya ya ya. buena vieja no me digas mas",
    "por quien has dado tan dañosos passos: desuergonçada baruuda",
    "no se dize en vano. que el mas empecible miembro del mal hombre o muger es la lengua: quemada seas alcahueta falsa. hechizera. enemiga de onestad. causadora de secretos yerros",
    "jesu jesu. quita me la lucrecia de delante que me fino: que no me ha dexado gota de sangre enel cuerpo",
    "Celestina. en hora mala aca vine",
    "Melibea. avn hablas entre dientes delante mi para acrecentar mi enojo",
    "Pues yo te certifico que las albricias que de aqui saques: no sean sino estoruar te de mas ofender a dios: dando fin a tus dias.",
    "Responde me traydora como osaste tanto fazer.",
    "lo que mas siento & me pena: es recibir enojo sin razon ninguna.",
    "Por dios señora que me dexes concluyr mi dicho",
    "veras como es todo mas seruicio de dios que passos deshonestos: mas para dar salud al enfermo que para dañar la fama al medico.",
    "Melibea. jesu no oyga yo mentar mas esso loco: salta paredes. fantasma de noche. luengo como ciguñal. figura de paramento mal pintado: si no aqui me caere muerta.",
    "Melibea. Este es el que el otro dia me vido: & començo a desuariar comigo en razones: haziendo mucho del galan.",
    "holgue mas de consentir sus necedades: que castigar su yerro: quise mas dexar le por loco que publicar su grande atreuimiento",
    "pues auisa le que se aparte deste proposito & ser le ha sano: si no podra ser que no aya comprado tan cara habla en su vida.",
    "Pues sabe que no es vencido sino el que se cree serlo",
    "Delos locos es estimar a todos los otros de su calidad",
    "respuesta de mi otra no hauras: ni la esperes",
    "da gracias a dios pues tan libre vas desta feria.",
    "Bien me hauian dicho quien tu eras: & auisado de tus propiedades",
    "Celestina. mas fuerte estaua troya: & avn otras mas brauas he yo amansado: ninguna tempestad mucho dura.",
    "Melibea. que dizes enemiga: fabla que te pueda oyr",
    "no me marauillo que la sangre nueua poco calor ha menester para heruir.",
    "que si falto el deuido preambulo: fue porque la verdad no es necessario abundar de muchas colores.",
    "pues conoces señora que el dolor turba: la turbacion desmanda & altera la lengua. La qual hauia de estar siempre atada conel seso",
    "no quiebre la soga por lo mas delgado no seas la telaraña que no muestra su fuerça sino contra los flacos animales.",
    "No paguen justos por pecadores. Imita la diuina justicia que dixo. El anima que pecare aquella misma muera: ala humana que jamas condena al padre por el delicto del hijo: ni al hijo por el del padre.",
    "que no es otro mi oficio sino seruir alos semejantes. Desto viuo & desto me arreo",
    "nunca fue mi voluntad enojar a vnos por agradar a otros: avn que ayan dicho a tu merced en mi absencia otra cosa",
    "que ayan dicho a tu merced en mi absencia otra cosa: al fin señora ala firme verdad: el viento del vulgo no la empece.",
    "que bien se que ni juramento ni tormento te torcera a dezir verdad: que no es en tu mano.",
    "tu mala palabra sera vispera de vna saya.",
    "concurrieron dos cosas en tu habla: que qualquiera dellas era bastante para me sacar de seso.",
    "Pero pues todo viene de buena parte: delo passado aya perdon",
    "en alguna manera es aliuiado mi coraçon: viendo que es obra pia & santa sanar los passionados & enfermos.",
    "Gracias dos mill. en franqueza Alexandre. en esfuerço Etor. gesto de vn rey. gracioso alegre: jamas reyna enel tristeza.",
    "De noble sangre como sabes. gran justador. Pues verle armado vn sant George. fuerça & esfuerço no tuuo Ercules tanta. la presencia & faciones. dispusicion. desemboltura. otra lengua hauia menester para las contar",
    "Por fe tengo que no era tan hermoso aquel gentil Narciso que se enamoro de su propia figura: quando se vido enlas aguas dela fuente.",
    "E el mayor remedio que tiene es tomar vna vihuela & tañe tantas canciones & tan lastimeras: que no creo que fueron otras las que compuso aquel emperador & gran musico Adriano",
    "que avn que yo se poco de musica: parece que faze aquella vihuela fablar.",
    "pues si a caso canta de mejor gana se paran las aues a le oyr que no aquel Antico: de quien se dize que mouia los arboles & piedras con su canto.",
    "ninguna muger le vee que no alabe a dios que assi le pinto.",
    "E pues tanta razon tengo juzga señora por bueno mi proposito: mis passos saludables & vazios de sospecha.",
    "Lucrecia. ya ya: perdida es mi ama: secretamente quiere que venga celestina: fraude ay: mas le querra dar que lo dicho.\nMelibea. que dizes lucrecia.\nLucrecia. señora que baste lo dicho que es tarde.",
    "Melibea. pues madre no le des parte delo que passo a ese cauallero: por que no me tenga por cruel o arrebatada o desonesta.",
    "dar te he vnos poluos para quitar te esse olor dela boca: que te huele vn poco",
    "se dize: que del ayrado es de apartar por poco tiempo: del enemigo por mucho.",
    "que cada dia ay hombres penados por mugeres: & mugeres por hombres. & esto obra la natura: & la natura ordeno la dios: & dios no hizo cosa mala",
    "mas razones destas te daria si no porque la prolixidad es enojosa al que oye: & dañosa al que habla.",
    "Melibea. en todo has tenido buen tiento: assi enlo poco hablar en mi enojo: como conel mucho sofrir.",
    "ve con dios que ni tu mensaje me ha traydo prouecho: ni de tu yda me puede venir daño.",
    "Celestina. O Rigurosos trances o cruda osadia o gran sofrimiento: & que tan cercana estuue dela muerte si mi mucha astucia no rigera con el tiempo: las velas dela peticion.",
    "o diablo a quien yo conjure: como compliste tu palabra en todo lo que te pedi: en cargo te soy: assi amansaste la cruel hembra con tu poder: & diste tan oportuno lugar a mi habla",
    "o vieja celestina vas alegre. sabete que la meytad esta hecha quando tienen buen principio las cosas.",
    "o yo rompiera todos mis atamientos hechos & por fazer ni creyera en yeruas ni en piedras ni en palabras.",
    "Pues alegrate vieja: que mas sacaras deste pleyto: que de quinze virgos que renouaras.",
    "o buena fortuna como ayudas alos osados: & alos timidos eres contraria. nunca huyendo huyo la muerte al couarde.",
    "o quantas erraran enlo que yo he acertado",
    "Por esto dizen quien las sabe las tañe: & que es mas cierto medico el esperimentado que el letrado: & la esperiencia & escarmiento haze los hombres arteros",
    "Sempronio. o yo no veo bien o aquella es celestina. valala el diablo haldear que trae: parlando viene entre dientes.",
    "quien jamas te vido por la calle abaxada la cabeça: puestos los ojos enel suelo: & no mirar a ninguno como agora",
    "quien te vido hablar entre dientes por las calles: & venir aguijando como quien va a ganar beneficio",
    "dime por dios con que vienes. dime si tenemos hijo o hija. que desde que dio la vna te espero aqui",
    "Celestina. calla loquillo: que parte o partezilla quanto tu quisieres te dare.",
    "Todo lo mio es tuyo: gozemonos & aprouechemonos: que sobre el partir nunca reñiremos.",
    "Sempronio. otras cosas he menester mas de comer.",
    "Sempronio. o lisonjera vieja. o vieja llena de mal. o cobdiciosa & auarienta garganta: tambien quiere a mi engañar como a mi amo",
    "que quien con modo torpe sube enlo alto: mas presto cae que sube.",
    "o que mala cosa es de conocer el hombre: bien dizen que ninguna mercaduria ni animal es tan dificil.",
    "mala vieja falsa es esta: el diablo me metio conella. mas seguro me fuera huyr desta venenosa biuora que tomalla",
    "Celestina. el proposito muda el sabio: el nescio perseuera. a nueuo negocio nueuo consejo se requiere.",
    "delos discretos mensajeros es fazer lo que el tiempo quiere",
    "que los acelerados & supitos plazeres crian alteracion: la mucha alteracion estorua el deliberar",
    "pues en que podra parar el bien sino en bien: & el alto mensaje sino en luengas albricias",
    "calla bouo dexa fazer a tu vieja.",
    "Celestina. calla loco: alterase te la complesion. yo lo veo en ti que querrias mas estar al sabor que al olor deste negocio",
    "o mis tristes oydos aparejaos alo que os viniere: que en su boca de celestina esta agora aposentado el aliuio o pena de mi coraçon.",
    "agora tengo por cierto que es mas penoso al delinquente esperar la cruda & capital sentencia que el acto dela ya sabida muerte.",
    "o espacioso parmeno manos de muerto. quita ya essa enojosa aldaua: entrara essa honrrada dueña: en cuya lengua esta mi vida.",
]
